/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NoiMobilityTraffic {
    }
}
declare global {
    interface HTMLNoiMobilityTrafficElement extends Components.NoiMobilityTraffic, HTMLStencilElement {
    }
    var HTMLNoiMobilityTrafficElement: {
        prototype: HTMLNoiMobilityTrafficElement;
        new (): HTMLNoiMobilityTrafficElement;
    };
    interface HTMLElementTagNameMap {
        "noi-mobility-traffic": HTMLNoiMobilityTrafficElement;
    }
}
declare namespace LocalJSX {
    interface NoiMobilityTraffic {
    }
    interface IntrinsicElements {
        "noi-mobility-traffic": NoiMobilityTraffic;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "noi-mobility-traffic": LocalJSX.NoiMobilityTraffic & JSXBase.HTMLAttributes<HTMLNoiMobilityTrafficElement>;
        }
    }
}
