/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NoiMobilityMap {
        "defaultPopup": string;
        "iconHeight": number;
        "iconUrl": string;
        "iconWidth": number;
        "latitude": number;
        "longitude": number;
        "scale": number;
        "showDefaultMarker": boolean;
        "showScale": boolean;
        "tileLayer": string;
        "userIconHeight": number;
        "userIconUrl": string;
        "userIconWidth": number;
        "userLatitude": number;
        "userLongitude": number;
    }
    interface NoiMobilityTraffic {
    }
}
declare global {
    interface HTMLNoiMobilityMapElement extends Components.NoiMobilityMap, HTMLStencilElement {
    }
    var HTMLNoiMobilityMapElement: {
        prototype: HTMLNoiMobilityMapElement;
        new (): HTMLNoiMobilityMapElement;
    };
    interface HTMLNoiMobilityTrafficElement extends Components.NoiMobilityTraffic, HTMLStencilElement {
    }
    var HTMLNoiMobilityTrafficElement: {
        prototype: HTMLNoiMobilityTrafficElement;
        new (): HTMLNoiMobilityTrafficElement;
    };
    interface HTMLElementTagNameMap {
        "noi-mobility-map": HTMLNoiMobilityMapElement;
        "noi-mobility-traffic": HTMLNoiMobilityTrafficElement;
    }
}
declare namespace LocalJSX {
    interface NoiMobilityMap {
        "defaultPopup"?: string;
        "iconHeight"?: number;
        "iconUrl"?: string;
        "iconWidth"?: number;
        "latitude"?: number;
        "longitude"?: number;
        "scale"?: number;
        "showDefaultMarker"?: boolean;
        "showScale"?: boolean;
        "tileLayer"?: string;
        "userIconHeight"?: number;
        "userIconUrl"?: string;
        "userIconWidth"?: number;
        "userLatitude"?: number;
        "userLongitude"?: number;
    }
    interface NoiMobilityTraffic {
    }
    interface IntrinsicElements {
        "noi-mobility-map": NoiMobilityMap;
        "noi-mobility-traffic": NoiMobilityTraffic;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "noi-mobility-map": LocalJSX.NoiMobilityMap & JSXBase.HTMLAttributes<HTMLNoiMobilityMapElement>;
            "noi-mobility-traffic": LocalJSX.NoiMobilityTraffic & JSXBase.HTMLAttributes<HTMLNoiMobilityTrafficElement>;
        }
    }
}
