name: CI/CD

on:
  push:
  pull_request:

env:
  NODE_VERSION: 16.x

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          X_CLIENT_ID: "it.bz.opendatahub.webcomponents.mobility-traffic"
          X_TOKEN_URL: "https://auth.opendatahub.com/auth/realms/noi/protocol/openid-connect/token"

      - name: Prepare stencil bin
        run: |
          mkdir -p ~/.local/bin
          ln -s "$PWD/node_modules/@stencil/core/bin/stencil" ~/.local/bin/stencil

      - uses: noi-techpark/github-actions/npm-test@v2
        with:
          lint-enabled: false
          node-version: ${{env.NODE_VERSION}}

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build:cdn
          node-version: ${{env.NODE_VERSION}}

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          X_CLIENT_ID: "it.bz.opendatahub.webcomponents.mobility-traffic"
          X_TOKEN_URL: "https://auth.opendatahub.com/auth/realms/noi/protocol/openid-connect/token"

      - name: Prepare stencil bin
        run: |
          mkdir -p ~/.local/bin
          ln -s "$PWD/node_modules/@stencil/core/bin/stencil" ~/.local/bin/stencil

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build:cdn
          node-version: ${{env.NODE_VERSION}}

      # npm run build:cdn builds files that can change name
      # so this command fills the wcs-manifest with that files
      - name: Fill wcs-manifest files
        run: sed -i 's/FILES_BY_CICD/'"$(ls cdn/noi/ | jq -R -s -c 'split("\n")[:-1]')"'/g' wcs-manifest.json


      - uses: noi-techpark/github-actions/webcomp-push@v2
        with:
          keycloak-secret: ${{secrets.WCSTORE_CLI_KEYCLOAK_SECRET_TEST}}
          version-tag: ${{github.sha}}

  deploy-prod:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    concurrency: deploy-prod
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          X_CLIENT_ID: "it.bz.opendatahub.webcomponents.mobility-traffic"
          X_TOKEN_URL: "https://auth.opendatahub.com/auth/realms/noi/protocol/openid-connect/token"

      - name: Prepare stencil bin
        run: |
          mkdir -p ~/.local/bin
          ln -s "$PWD/node_modules/@stencil/core/bin/stencil" ~/.local/bin/stencil

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build:cdn
          node-version: ${{env.NODE_VERSION}}

      # npm run build:cdn builds files that can change name
      # so this command fills the wcs-manifest with that files
      - name: Fill wcs-manifest files
        run: sed -i 's/FILES_BY_CICD/'"$(ls cdn/noi/ | jq -R -s -c 'split("\n")[:-1]')"'/g' wcs-manifest.json

      - uses: noi-techpark/github-actions/webcomp-push@v2
        with:
          keycloak-secret: ${{secrets.WCSTORE_CLI_KEYCLOAK_SECRET_PROD}}
          version-tag: ${{github.ref_name}}
          production: "true"
